### ISSUE TITLE
Support for tramp-copy-program

### ISSUE THREAD

**Issue by danlamanna** [emacs-pe/docker-tramp.el#14]
I fiddled with `tramp-copy-program` and `tramp-copy-args` for a little bit with no success as I'm unfamiliar with tramp internals.

Ideally these would be set so using things like `dired` for copying/renaming would work across docker containers and anything else supported with tramp.

Docker usage is very straightforward after v1.8:

```
docker cp foo.txt mycontainer:/foo.txt
docker cp mycontainer:/foo.txt foo.txt
```

Thanks for the great package!

**Comment by marsam** [comment]
Hi, sorry for the late response. I'm going to reopen to issue, I'm not sure if is possible, but i'll check it this weekend.

**Comment by danlamanna** [comment]
Actually I closed it because this works as intended.

The issue I was having is it not working with dired-async, which I think might be a problem with that package (though I'm not positive).
