### ISSUE TITLE
Please upload to MELPA Stable

### ISSUE THREAD

**Issue by mwolson** [emacs-pe/docker-tramp.el#15]
It would be great to have this package on MELPA Stable for easier installing.

**Comment by marsam** [comment]
Hi sorry for the delay, I've created the tag so I think should be matter of time available in melpa stable

**Comment by mwolson** [comment]
Works great, thanks!

**Comment by phikal** [comment]
On this topic, I'd like to add the package to [NonGNU ELPA](http://elpa.nongnu.org/). The only thing necessary for that would be to update the [Version attribute](https://github.com/emacs-pe/docker-tramp.el/blob/master/docker-tramp.el#L8) in the main file. Would there be any interest in that?

**Comment by marsam** [comment]
@phikal I'm so sorry for the late response. I've bumped v0.1.1, please let me know if there is anything else I can do to help you.

**Comment by phikal** [comment]
That should be it, but if you don't mind I have a few questions about the code:

- Why are constants like `docker-tramp-docker-executable` autoloaded?
- Would you mind replacing `docker-tramp--running-containers` with a more stable implementation like
~~~elisp
(with-temp-buffer
  (apply #'call-process docker-tramp-docker-executable nil t nil
	 (append docker-tramp-docker-options
		 (list "ps" "--format" "{{.ID}}\036{{.Names}}")))
  (let (containers)
    (while (search-backward-regexp "^\\(.+\\)\036\\(.+\\)$" nil t)
      (push (cons (match-string 1) (match-string 2))
	    containers))
    containers))
~~~

I am not a docker expert, so you should double check if this is ok.
- Have you considered adding [tramp](http://elpa.gnu.org/packages/tramp.html) as an explicit dependency, so as to avoid having to bundle the compat file?  The downside to this is that you transitivly raise the minimum version to 25.

Also I should point out the [NonGNU ELPA rules for admission](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/README.org?h=elpa-admin#n120).  From what I see everything is ok, but I just want to make sure you know about it.
