### ISSUE TITLE
Possible to Use When Docker Not Installed Locally?

### ISSUE THREAD

**Issue by julienchastang** [emacs-pe/docker-tramp.el#25]
This is a great project that has saved me a lot of time.

Is it possible to access *remote* docker containers on other hosts when docker is not installed locally?

I'm trying to use this project from my Android device with no Docker installation possible and helm-tramp complains about not finding docker.

**Comment by marsam** [comment]
Right now `docker-tramp` depends on the docker executable, but I think it we could use [Docker API](https://docs.docker.com/engine/api/v1.39/#tag/Exec) directly.
Unfortunately, [docker-api.el](https://github.com/Silex/docker-api.el) is sill in early-development stage, and I don't have time to work on this.

**Comment by p3r7** [comment]
In fact you can with [tramp multi hops](https://www.gnu.org/software/emacs/manual/html_node/tramp/Ad_002dhoc-multi_002dhops.html).

You need to first hop onto the remote docker host with a supported protocol (e.g. ssh) and then rely on the docker command on this host.

For example : `/ssh:192.168.0.2|docker:container:/`
