### ISSUE TITLE
Package is loaded on Emacs startup despite not explicitly loading it

### ISSUE THREAD

**Issue by doolio** [emacs-pe/docker-tramp.el#38]
I only load a select number of packages on Emacs startup and this is not one. However, I note it is loaded in any case.

**Comment by PuercoPop** [comment]
Is tramp one of the packages that you are loading? If so this would explain why.

https://github.com/emacs-pe/docker-tramp.el/blob/930d7b46c180d8a13240a028c1b40af84f2a3219/docker-tramp.el#L168-L172

**Comment by doolio** [comment]
It's not one I explicitly load either but checking now it seems my Emacs does. I should have checked for such an `eval-after-load`. Thanks for pointing it out. I'll close this now. Sorry for the noise.
