### ISSUE TITLE
docker-tramp autoload

### ISSUE THREAD

**Issue by guillaumekoenig** [emacs-pe/docker-tramp.el#4]
Hi there,

Thanks for docker-tramp, it's been very useful to me. Quick observation though : method isn't available before explicit loading (with "require" by example).

Looking at tramp-docker-autoloads.el, the autoloads where not generated completely (ie only docker-tramp-cleanup is present).

The definitions in docker-tramp.el are preceded by the line ;;;###tramp-autoload. Is it meant to be used with a custom value of generate-autoload-cookie ? Otherwise why not simply use ;;;###autoload (default value) ?

**Comment by marsam** [comment]
Hi:
Sorry for the late response. I've pushed a fix for this issue, feel free to reopen it if doesn't works for you.

>  [the docker] method isn't available before explicit loading (with "require" by example).

I'm newbie to the autload system in Emacs, so I thought to make this package to be loaded to be used.

> The definitions in docker-tramp.el are preceded by the line ;;;###tramp-autoload. Is it meant to be used with a custom value of generate-autoload-cookie ? Otherwise why not simply use ;;;###autoload (default value) ?

I mostly based in other `tramp-` methods included in Emacs, the `tramp-autoload` cookie is meant to generate the `tramp-loadefs.el` when compiling Emacs, and you are right doesn't make much sense in this package.

**Comment by guillaumekoenig** [comment]
It's working for me now. docker-tramp is autoloaded and I can access /docker: paths. Thanks :-)
