### ISSUE TITLE
Documentation does not describe syntax

### ISSUE THREAD

**Issue by udalrich** [emacs-pe/docker-tramp.el#9]
The documentation does not give an example of how to use it.  To edit /bar in the foo container, do I do enter

*  `docker:user@foo:/bar`
* `ssh:user@foo/bar`
* something else?

**Comment by marsam** [comment]
Hi:
I've added the usage in the readme, tell me if it works for you

**Comment by udalrich** [comment]
I haven't tried it, but the text looks good.
